version: '2'
services:
  cas-postgres:
    image: "postgres:14-alpine"
    restart: 
      always
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=cas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456